### ISSUE TITLE
Precompiled version?

### ISSUE THREAD

**Issue by Bluscream** [fortinmike/vsclean#1]
I would like it to cleanup all my VS folders

**Comment by fortinmike** [comment]
Hi, @Bluscream! The tool is distributed as a ruby gem so you need to install Ruby then simply run "gem install vsclean" in cmd. There is no exe installer. If you have any other questions ask away!

**Comment by Bluscream** [comment]
Okay, i found a c# alternative, thanks

**Comment by fortinmike** [comment]
For others finding this issue, would you share a link to the other tool you found? Might be useful to many.

Also, if the tool in question doesn't do what you want in the end, give vsclean a shot. It fixes most of the issues we've had over time (which there are a lot of), and it's the result of multiple hours of tearing our hair out figuring out weird Visual Studio errors.
